apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: java-springboot-elkkjsen
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/java-springboot-elkkjsen:f993a78b794df9121cba0d34bff2b37bd2ba663c@sha256:1a3da884cfd148d0e57d5e10edc1e5b62e1f965c9e1b715734628f3ceaf5976b
          name: container-image
